### ISSUE TITLE
Error on Camera use

### ISSUE THREAD

**Issue by UrbanSide** [ShahabGT/InstagramPicker#4]
```
2020-04-12 14:19:59.215 19825-19989/com.box.a100rados E/AndroidRuntime: FATAL EXCEPTION: Camera
    Process: com.box.a100rados, PID: 19825
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2426)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:765)
        at ir.shahabazimi.instagrampicker.gallery.CameraFragment.createCameraPreview(CameraFragment.java:248)
        at ir.shahabazimi.instagrampicker.gallery.CameraFragment.access$100(CameraFragment.java:63)
        at ir.shahabazimi.instagrampicker.gallery.CameraFragment$3.onCaptureCompleted(CameraFragment.java:215)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3(CameraCaptureSessionImpl.java:641)
        at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$OA1Yz_YgzMO8qcV8esRjyt7ykp4.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by ShahabGT** [comment]
fixed in version 2.1.0
