### ISSUE TITLE
Error on single file use

### ISSUE THREAD

**Issue by UrbanSide** [ShahabGT/InstagramPicker#6]
When i select one file i have this error
```
2020-06-06 11:20:43.646 8879-8879/com.box.a100rados E/APP: subscribeToTopic
2020-06-06 11:20:43.651 8879-8879/com.box.a100rados E/m.box.a100rado: Invalid ID 0x00000000.
2020-06-06 11:20:52.497 8879-9252/com.box.a100rados E/timeData: 1591431021
2020-06-06 11:21:10.207 8879-8879/com.box.a100rados E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.box.a100rados, PID: 8879
    java.lang.RuntimeException: Error receiving broadcast Intent { act=refreshPlease flg=0x10 } in ir.shahabazimi.instagrampicker.InstagramPicker$1@a04de7a
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void ir.shahabazimi.instagrampicker.SingleListener.selectedPic(java.lang.String)' on a null object reference
        at ir.shahabazimi.instagrampicker.InstagramPicker$1.onReceive(InstagramPicker.java:80)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2020-06-06 11:21:10.403 8879-8879/com.box.a100rados E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.RuntimeException: Error receiving broadcast Intent { act=refreshPlease flg=0x10 } in ir.shahabazimi.instagrampicker.InstagramPicker$1@a04de7a
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1407)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void ir.shahabazimi.instagrampicker.SingleListener.selectedPic(java.lang.String)' on a null object reference
        at ir.shahabazimi.instagrampicker.InstagramPicker$1.onReceive(InstagramPicker.java:80)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1397)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 

```

**Comment by ShahabGT** [comment]
Fixed
